# Generated by Django 3.1.3 on 2020-12-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=100)),
                ('back', models.CharField(max_length=100)),
                ('deck_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remembo.deck')),
            ],
        ),
    ]
