# Generated by Django 3.1.3 on 2020-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_bookmark',
            field=models.CharField(default='', max_length=20),
        ),
    ]
